-- Gerado por Oracle SQL Developer Data Modeler 4.1.3.901
--   em:        2025-04-18 23:26:27 BRT
--   site:      Oracle Database 11g
--   tipo:      Oracle Database 11g




DROP TABLE T_APLICACAO_INSUMO CASCADE CONSTRAINTS ;

DROP TABLE T_APLICADOR CASCADE CONSTRAINTS ;

DROP TABLE T_COMPRA CASCADE CONSTRAINTS ;

DROP TABLE T_CULTURA CASCADE CONSTRAINTS ;

DROP TABLE T_FAZENDA CASCADE CONSTRAINTS ;

DROP TABLE T_FORNECEDOR CASCADE CONSTRAINTS ;

DROP TABLE T_FUNCIONARIO CASCADE CONSTRAINTS ;

DROP TABLE T_INSUMO CASCADE CONSTRAINTS ;

DROP TABLE T_INSUMO_CULTURA CASCADE CONSTRAINTS ;

DROP TABLE T_ITEM_COMPRA CASCADE CONSTRAINTS ;

DROP TABLE T_LEITURA CASCADE CONSTRAINTS ;

DROP TABLE T_PLANTACAO CASCADE CONSTRAINTS ;

DROP TABLE T_SENSOR CASCADE CONSTRAINTS ;

DROP TABLE T_UNIDADE_MEDIDA CASCADE CONSTRAINTS ;

CREATE TABLE T_APLICACAO_INSUMO
  (
    cd_aplicacao INTEGER NOT NULL ,
    cd_insumo    INTEGER NOT NULL ,
    cd_aplicador INTEGER NOT NULL ,
    cd_plantacao INTEGER NOT NULL ,
    quantidade   NUMBER (5,2) NOT NULL ,
    tipo         VARCHAR2 (50) NOT NULL ,
    dt_aplicacao TIMESTAMP NOT NULL
  ) ;
ALTER TABLE T_APLICACAO_INSUMO ADD CONSTRAINT CK_APLICACAO_INSUMO_QTD CHECK (quantidade > 0) ;
ALTER TABLE T_APLICACAO_INSUMO ADD CONSTRAINT PK_T_APLICACAO_INSUMO PRIMARY KEY ( cd_aplicacao ) ;


CREATE TABLE T_APLICADOR
  (
    cd_aplicador INTEGER NOT NULL ,
    cd_fazenda   INTEGER NOT NULL ,
    nome         VARCHAR2 (100) NOT NULL ,
    tipo         VARCHAR2 (50) NOT NULL
  ) ;
ALTER TABLE T_APLICADOR ADD CONSTRAINT PK_T_APLICADOR PRIMARY KEY ( cd_aplicador ) ;


CREATE TABLE T_COMPRA
  (
    cd_compra     INTEGER NOT NULL ,
    cd_fazenda    INTEGER NOT NULL ,
    cd_fornecedor INTEGER NOT NULL ,
    valor_total   NUMBER (7,2) NOT NULL ,
    dt_compra     TIMESTAMP NOT NULL
  ) ;
ALTER TABLE T_COMPRA ADD CONSTRAINT PK_T_COMPRA PRIMARY KEY ( cd_compra ) ;


CREATE TABLE T_CULTURA
  (
    cd_cultura        INTEGER NOT NULL ,
    nome              VARCHAR2 (100) NOT NULL ,
    tipo              VARCHAR2 (50) NOT NULL ,
    tmp_colheita_dias INTEGER NOT NULL
  ) ;
ALTER TABLE T_CULTURA ADD CONSTRAINT PK_T_CULTURA PRIMARY KEY ( cd_cultura ) ;
ALTER TABLE T_CULTURA ADD CONSTRAINT UN_T_CULTURA_nome UNIQUE ( nome ) ;


CREATE TABLE T_FAZENDA
  (
    cd_fazenda INTEGER NOT NULL ,
    cnpj       CHAR (14) NOT NULL ,
    nome       VARCHAR2 (50) NOT NULL ,
    endereco   VARCHAR2 (100) NOT NULL ,
    telefone   VARCHAR2 (11) NOT NULL
  ) ;
ALTER TABLE T_FAZENDA ADD CONSTRAINT PK_T_FAZENDA PRIMARY KEY ( cd_fazenda ) ;
ALTER TABLE T_FAZENDA ADD CONSTRAINT UN_T_FAZENDA_cnpj_nome UNIQUE ( cnpj , nome ) ;


CREATE TABLE T_FORNECEDOR
  (
    cd_fornecedor INTEGER NOT NULL ,
    cnpj          CHAR (14) NOT NULL ,
    nome          VARCHAR2 (100) NOT NULL ,
    email         VARCHAR2 (50) NOT NULL ,
    telefone      VARCHAR2 (11) NOT NULL
  ) ;
ALTER TABLE T_FORNECEDOR ADD CONSTRAINT PK_T_FORNECEDOR PRIMARY KEY ( cd_fornecedor ) ;
ALTER TABLE T_FORNECEDOR ADD CONSTRAINT UN_T_FORNECEDOR_cnpj UNIQUE ( cnpj ) ;


CREATE TABLE T_FUNCIONARIO
  (
    cd_funcionario  INTEGER NOT NULL ,
    cd_fazenda      INTEGER NOT NULL ,
    cpf             CHAR (11) NOT NULL ,
    email           VARCHAR2 (50) NOT NULL ,
    salario         NUMBER (7,2) NOT NULL ,
    nome            VARCHAR2 (50) NOT NULL ,
    telefone        VARCHAR2 (11) NOT NULL ,
    endereco        VARCHAR2 (100) NOT NULL ,
    dt_contratacao  DATE NOT NULL ,
    dt_desligamento DATE ,
    salario1        NUMBER (7,2) NOT NULL
  ) ;
ALTER TABLE T_FUNCIONARIO ADD CONSTRAINT CK_FUNC_SALARIO CHECK (salario                  >= 1518) ;
ALTER TABLE T_FUNCIONARIO ADD CONSTRAINT CK_FUNC_DT_DESLIGAMENTO CHECK (data_desligamento > data_contratacao) ;
ALTER TABLE T_FUNCIONARIO ADD CONSTRAINT PK_T_FUNCIONARIO PRIMARY KEY ( cd_funcionario ) ;
ALTER TABLE T_FUNCIONARIO ADD CONSTRAINT UN_T_FUNCIONARIO_cpf UNIQUE ( cpf ) ;


CREATE TABLE T_INSUMO
  (
    cd_insumo         INTEGER NOT NULL ,
    cd_unidade_medida INTEGER NOT NULL ,
    nome              VARCHAR2 (100) NOT NULL ,
    tipo              VARCHAR2 (50) NOT NULL ,
    unidade_medida    VARCHAR2 (10) NOT NULL
  ) ;
ALTER TABLE T_INSUMO ADD CONSTRAINT PK_T_INSUMO PRIMARY KEY ( cd_insumo ) ;
ALTER TABLE T_INSUMO ADD CONSTRAINT UN_T_INSUMO_nome UNIQUE ( nome ) ;


CREATE TABLE T_INSUMO_CULTURA
  (
    cd_cultura INTEGER NOT NULL ,
    cd_insumo  INTEGER NOT NULL ,
    quantidade NUMBER (5,2) NOT NULL
  ) ;
ALTER TABLE T_INSUMO_CULTURA ADD CONSTRAINT CK_INSUMO_CULTURA_QTD CHECK (quantidade > 0) ;
ALTER TABLE T_INSUMO_CULTURA ADD CONSTRAINT PK_T_INSUMO_CULTURA PRIMARY KEY ( cd_cultura, cd_insumo ) ;


CREATE TABLE T_ITEM_COMPRA
  (
    cd_item    INTEGER NOT NULL ,
    cd_compra  INTEGER NOT NULL ,
    cd_insumo  INTEGER NOT NULL ,
    descricao  VARCHAR2 (100) ,
    valor_uni  NUMBER (7,2) NOT NULL ,
    quantidade NUMBER (7,2) NOT NULL
  ) ;
ALTER TABLE T_ITEM_COMPRA ADD CONSTRAINT PK_T_ITEM_COMPRA PRIMARY KEY ( cd_item, cd_compra ) ;


CREATE TABLE T_LEITURA
  (
    dt_leitura TIMESTAMP NOT NULL ,
    cd_sensor  INTEGER NOT NULL ,
    valor      NUMBER (7,2) NOT NULL
  ) ;
ALTER TABLE T_LEITURA ADD CONSTRAINT PK_T_LEITURA PRIMARY KEY ( cd_sensor, dt_leitura ) ;


CREATE TABLE T_PLANTACAO
  (
    cd_plantacao      INTEGER NOT NULL ,
    cd_fazenda        INTEGER NOT NULL ,
    cd_cultura        INTEGER NOT NULL ,
    largura           NUMBER (7,2) NOT NULL ,
    altura            NUMBER (7,2) NOT NULL ,
    dt_inicio_plantio DATE NOT NULL ,
    dt_colheita       DATE
  ) ;
CREATE UNIQUE INDEX IDX_PLANTACAO ON T_PLANTACAO
  (
    cd_cultura ASC
  )
  ;
ALTER TABLE T_PLANTACAO ADD CONSTRAINT PK_T_PLANTACAO PRIMARY KEY ( cd_plantacao ) ;


CREATE TABLE T_SENSOR
  (
    cd_sensor  INTEGER NOT NULL ,
    cd_fazenda INTEGER NOT NULL ,
    tipo       VARCHAR2 (50) NOT NULL ,
    nome       VARCHAR2 (100) NOT NULL ,
    ativado    CHAR (1) ,
    posicao_x  NUMBER (3,2) NOT NULL ,
    posicao_y  NUMBER (3,2) NOT NULL
  ) ;
ALTER TABLE T_SENSOR ADD CONSTRAINT PK_T_SENSOR PRIMARY KEY ( cd_sensor ) ;


CREATE TABLE T_UNIDADE_MEDIDA
  (
    cd_unidade_medida INTEGER NOT NULL ,
    nome              VARCHAR2 (30) NOT NULL ,
    sigla             VARCHAR2 (5) NOT NULL
  ) ;
ALTER TABLE T_UNIDADE_MEDIDA ADD CONSTRAINT PK_T_UNIDADE_MEDIDA PRIMARY KEY ( cd_unidade_medida ) ;


ALTER TABLE T_APLICADOR ADD CONSTRAINT FK_T_APLICADOR_T_FAZENDA FOREIGN KEY ( cd_fazenda ) REFERENCES T_FAZENDA ( cd_fazenda ) ;

ALTER TABLE T_APLICACAO_INSUMO ADD CONSTRAINT FK_T_APLI_INS_T_APLICDR FOREIGN KEY ( cd_aplicador ) REFERENCES T_APLICADOR ( cd_aplicador ) ;

ALTER TABLE T_APLICACAO_INSUMO ADD CONSTRAINT FK_T_APLI_INS_T_INS FOREIGN KEY ( cd_insumo ) REFERENCES T_INSUMO ( cd_insumo ) ;

ALTER TABLE T_APLICACAO_INSUMO ADD CONSTRAINT FK_T_APLI_INS_T_PLANT FOREIGN KEY ( cd_plantacao ) REFERENCES T_PLANTACAO ( cd_plantacao ) ;

ALTER TABLE T_COMPRA ADD CONSTRAINT FK_T_COMPRA_T_FAZENDA FOREIGN KEY ( cd_fazenda ) REFERENCES T_FAZENDA ( cd_fazenda ) ;

ALTER TABLE T_COMPRA ADD CONSTRAINT FK_T_COMPRA_T_FORNECEDOR FOREIGN KEY ( cd_fornecedor ) REFERENCES T_FORNECEDOR ( cd_fornecedor ) ;

ALTER TABLE T_FUNCIONARIO ADD CONSTRAINT FK_T_FUNCIONARIO_T_FAZENDA FOREIGN KEY ( cd_fazenda ) REFERENCES T_FAZENDA ( cd_fazenda ) ;

ALTER TABLE T_INSUMO_CULTURA ADD CONSTRAINT FK_T_INSUMO_CULTURA_T_CULTURA FOREIGN KEY ( cd_cultura ) REFERENCES T_CULTURA ( cd_cultura ) ;

ALTER TABLE T_INSUMO_CULTURA ADD CONSTRAINT FK_T_INSUMO_CULTURA_T_INSUMO FOREIGN KEY ( cd_insumo ) REFERENCES T_INSUMO ( cd_insumo ) ;

ALTER TABLE T_INSUMO ADD CONSTRAINT FK_T_INSUMO_T_UNIDADE_MEDIDA FOREIGN KEY ( cd_unidade_medida ) REFERENCES T_UNIDADE_MEDIDA ( cd_unidade_medida ) ;

ALTER TABLE T_ITEM_COMPRA ADD CONSTRAINT FK_T_ITEM_COMPRA_T_COMPRA FOREIGN KEY ( cd_compra ) REFERENCES T_COMPRA ( cd_compra ) ;

ALTER TABLE T_ITEM_COMPRA ADD CONSTRAINT FK_T_ITEM_COMPRA_T_INSUMO FOREIGN KEY ( cd_insumo ) REFERENCES T_INSUMO ( cd_insumo ) ;

ALTER TABLE T_LEITURA ADD CONSTRAINT FK_T_LEITURA_T_SENSOR FOREIGN KEY ( cd_sensor ) REFERENCES T_SENSOR ( cd_sensor ) ;

ALTER TABLE T_PLANTACAO ADD CONSTRAINT FK_T_PLANTACAO_T_CULTURA FOREIGN KEY ( cd_cultura ) REFERENCES T_CULTURA ( cd_cultura ) ;

ALTER TABLE T_PLANTACAO ADD CONSTRAINT FK_T_PLANTACAO_T_FAZENDA FOREIGN KEY ( cd_fazenda ) REFERENCES T_FAZENDA ( cd_fazenda ) ;

ALTER TABLE T_SENSOR ADD CONSTRAINT FK_T_SENSOR_T_FAZENDA FOREIGN KEY ( cd_fazenda ) REFERENCES T_FAZENDA ( cd_fazenda ) ;


-- Relatório do Resumo do Oracle SQL Developer Data Modeler: 
-- 
-- CREATE TABLE                            14
-- CREATE INDEX                             1
-- ALTER TABLE                             39
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
